[package]
name = "pel"
version = "0.1.0"
authors = ["Matthew Russo <matthew@matthewclayrusso.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1.3.4"
lazy_static = "1.4.0"
either = "1.5.3"
